inOutServer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('inout.urls')),
    path('usuario/', include('usuario.urls'))
]

handler404 = 'inout.views.error_404_view'
handler500 = 'inout.views.error_500_view'

inout/urls.py
from django.urls import path
from django.conf.urls import url, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views
#from inout.views import lista_protocolos

app_name = "inout"
urlpatterns = [
	#path('', views.index, name = 'index'),
	#path('', views.login_view, name = 'login_view'),
	path('', views.login_view, name = 'login_view'),
	path('login', views.login_view, name = 'login_view'),
	path('login.html', views.login_view, name = 'login_view'),
	path('valida_login', views.valida_login, name = 'valida_login'),
	path('logout', views.logout_view, name = 'logout_view'),
	path('index', views.index, name = 'index'),
	path('index.html', views.index, name = 'index'),
	path('cadastrar', views.cadastrar, name = 'cadastrar'),
	path('cadastrar.html', views.cadastrar, name = 'cadastrar'),
	path('salvarcadastro', views.salvarcadastro, name = 'salvarcadastro'),
	path('<int:documento_id>/editar_documento', views.editar_documento, name = 'editar_documento'),
	path('<int:documento_id>/salvar_edicao_documento', views.salvar_edicao_documento, name = 'salvar_edicao_documento'),
	re_path(r'^protocolar_documento', views.protocolar_documento, name = "protocolar_documento"),
	re_path(r'^salvar_protocolo_documento', views.salvar_protocolo_documento, name = "salvar_protocolo_documento"),
	path('<int:protocolo_documento_id>/documento_entregue', views.documento_entregue, name = "documento_entregue"),
	path('listardocumentos', views.listardocumentos, name = 'listardocumentos'),
	path('listardocumentos.html', views.listardocumentos, name = 'listardocumentos'),
	path('<int:documento_id>/detalhesdocumento', views.detalhesdocumento, name = 'detalhesdocumento'),
	path('<int:documento_id>/detalhesdocumento.html', views.detalhesdocumento, name = 'detalhesdocumento'),
	path('<int:documento_id>/<int:prazo_id>/alterar_status_prazo', views.alterar_status_prazo, name = 'alterar_status_prazo'),
	path('listarprazos', views.listarprazos, name = 'listarprazos'),
	path('listarprazos.html', views.listarprazos, name = 'listarprazos'),
	path('listarprazosdodia', views.listarprazosdodia, name = 'listarprazosdodia'),
	path('listarprazosdodia.html', views.listarprazosdodia, name = 'listarprazosdodia'),
	path('listar_documentos_do_dia', views.listar_documentos_do_dia, name = 'listar_documentos_do_dia'),
	path('listar_documentos_da_semana', views.listar_documentos_da_semana, name = 'listar_documentos_da_semana'),
	path('listar_documentos_do_mes', views.listar_documentos_do_mes, name = 'listar_documentos_do_mes'),
	re_path(r'^novo_orgao', views.novo_orgao, name = 'novo_orgao'),
	re_path(r'^salvar_orgao', views.salvar_orgao, name = 'salvar_orgao'),
	re_path(r'^lista_orgaos', views.lista_orgaos , name = "lista_orgaos"),
	re_path(r'^novo_setor', views.novo_setor , name = "novo_setor"),
	re_path(r'^salvar_setor', views.salvar_setor , name = "salvar_setor"),
	re_path(r'^lista_setores', views.lista_setores , name = "lista_setores"),
	re_path(r'^novo_protocolo', views.novo_protocolo , name = "novo_protocolo"),
	re_path(r'^salvar_protocolo', views.salvar_protocolo , name = "salvar_protocolo"),
	re_path(r'^lista_protocolos_externos', views.lista_protocolos_externos , name = "lista_protocolos_externos"),
	re_path(r'^lista_protocolos_internos', views.lista_protocolos_internos , name = "lista_protocolos_internos"),
	re_path(r'^lista_protocolos_usf', views.lista_protocolos_usf , name = "lista_protocolos_usf"),
	re_path(r'^lista_protocolos', views.lista_protocolos.as_view(), name = "lista_protocolos"),
	re_path(r'^busca_numero_documento', views.busca_numero_documento, name = 'busca_numero_documento'),
	url(r'^api/chart/data/$', views.chart_data_linha.as_view()),
	url(r'^api/chart/pie/$', views.chart_data_pie.as_view()),
	#Falta implementar
	#re_path(r'^busca_avancada', views.busca_avancada , name = "busca_avancada"),
	re_path(r'^busca_avancada', views.busca_avancada.as_view() , name = "busca_avancada"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inout/views.py
from django.views.generic import ListView, TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, Http404
from django.urls import reverse
from django.template import loader
from .models import Documento, Prazo, Processo, Orgao, Setor, Livro, Pagina, Protocolo, Lotacao
from django.db import connections
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from rest_framework.views import APIView
from rest_framework.response import Response
import datetime

cursor_mysql = connections['default'].cursor()
cursor_postgresql = connections['postgresql'].cursor()

#Metodos de controle

#View responsável por chamar o template da página de login
def login_view(request):

	return render(request, 'registration/login.html')

#View responsável por validar as credenciais recebidas no template de login
def valida_login(request):
	user = authenticate(request, username = request.POST['nome_de_usuario'], password = request.POST['senha'])

	if user is not None:
		login(request, user)
		#Recupera o parametro next
		next = request.POST.get('next', False)

		if next:
			return redirect(reverse("{}{}".format('inout:', next.replace('/', '').replace('.html', ''))))
		else:
			return redirect(reverse('inout:index'))
	else:
		erro = {
			'erro': "Credenciais Inválidas",
		}

		#Renderiza a página de login novamente, com o adicional de uma mensagem de erro
		return render(request, 'registration/login.html', erro)

#View responsável por deslogar um usuário
def logout_view(request):
	#O try/except é necessário pro caso de acontecer uma tentativa de deletar uma sessão que não existe
	try:
		#Exclui a sessão
		logout(request)
		#del request.session['user_id']
	except KeyError:
		#Não faz nada
		pass

	#Redireciona para a página de login
	return redirect(reverse('inout:login_view'))

#View responsável por exibir a página inicial
@login_required
def index(request):
	#Filtra todos os documentos com prazo na data de hoje
	lista_de_documentos = prazos_do_dia()
	##Filtra todos os documentos cadastrados na data de hoje
	feitos_hoje = documentos_do_dia()
	#Filtra todos os documentos cadastrados na semana atual
	feitos_semana = documentos_da_semana()
	#Filtra todos os documentos cadastrados no mês atual
	feitos_mes = documentos_do_mes()

	#O contexto armazena as 4 informações coletadas nas linhas acima, as mesmas serão exibidas nos 4 cards presentes na página inicial
	contexto = {
		'quantidade_de_prazos_do_dia': len(lista_de_documentos),
		'feitos_hoje': len(feitos_hoje),
		'feitos_semana': len(feitos_semana),
		'feitos_mes': len(feitos_mes),
	}

	#Renderiza a página de login com o contexto gerado
	return render(request, 'index.html', contexto)

	""" Tambem é possivel verificar o login para permitir o acesso as paginas usando a seguinte estrutura:
	if request.user.is_autheticated:
		faz alguma coisa
	else:
		redireciona para outra página """

@login_required
def cadastrar(request):
	prazo = Prazo()

	contexto = {
		'titulo': "Cadastrar novo documento",
		'lista_de_tipos_de_prazo': prazo.tipo_choices
	}

	return render(request, 'inout/cadastrar.html', contexto)

#def responsavel apenas por processar dados, não carrega um template de página, apenas faz o redirecionamento para uma outra def que possua um template
@login_required
def salvarcadastro(request):
	if request.method == 'POST':
		#Cada request.POST é responsável por capturar um dado especifico do formulário, esse dado é representado pelo seu name no input do form
		""" documento = Documento()
		documento.fk_user = request.user
		documento.data_de_recebimento = datetime.date.today()
		documento.tipo = int(request.POST['tipo_de_documento'])
		documento.numero = request.POST['numero_do_documento']
		documento.emissor = request.POST['orgao_expedidor_do_documento']
		documento.assunto = request.POST['assunto_do_documento']
		documento.despacho = request.POST['despacho_do_documento'] """

		cursor_mysql.execute('INSERT INTO documento '
								+ '(fk_user, data_de_recebimento, tipo, numero, emissor, assunto, despacho, entrega_pessoal) '
							+ 'VALUES '
								+ '(%s, %s, %s, %s, %s, %s, %s, %s)', [
																		request.user.id,
																		datetime.date.today(),
																		int(request.POST['tipo_de_documento']),
																		request.POST['numero_do_documento'],
																		request.POST['orgao_expedidor_do_documento'],
																		request.POST['assunto_do_documento'],
																		request.POST['despacho_do_documento'],
																		request.POST.get('entrega_pessoal', False),
																		])
		cursor_mysql.execute('SELECT MAX(id) FROM documento')
		documento_id = cursor_mysql.fetchone()[0]

		documento_pdf = Documento.objects.using('default').get(pk = documento_id)
		documento_pdf.pdf = request.FILES["pdf"]
		documento_pdf.save()

		cursor_postgresql.execute('INSERT INTO documento '
									+ '(fk_user, data_de_recebimento, tipo, numero, emissor, assunto, despacho, entrega_pessoal) '
								+ 'VALUES '
									+ '(%s, %s, %s, %s, %s, %s, %s, %s)', [
																			request.user.id,
																			datetime.date.today(),
																			int(request.POST['tipo_de_documento']),
																			request.POST['numero_do_documento'],
																			request.POST['orgao_expedidor_do_documento'],
																			request.POST['assunto_do_documento'],
																			request.POST['despacho_do_documento'],
																			request.POST.get('entrega_pessoal', False),
																			])
		cursor_postgresql.execute('SELECT MAX(id) FROM documento')
		documento_id = cursor_postgresql.fetchone()[0]

		documento_pdf = Documento.objects.using('postgresql').get(pk = documento_id)
		documento_pdf.pdf = request.FILES["pdf"]
		documento_pdf.save()

		""" try:
			#Tenta recuperar o objeto do processo com o número informado no formulário
			processo = Processo.objects.get(numero = request.POST['numero_do_processo'])
			#Caso seja, o documento é associado ao processo
			documento.processo = processo
		except Processo.DoesNotExist:
			#Caso não seja, é criado um novo processo, e então o documento é associado a ele
			novo_processo = Processo()
			novo_processo.numero = request.POST['numero_do_processo']
			novo_processo.save()
			documento.processo = novo_processo """

		processo = request.POST.get('numero_do_processo', False)
		if processo:
			objeto_processo = Processo.objects.using('default').raw('SELECT * FROM processo WHERE numero = %s', [processo])
			if objeto_processo:
				#with connection.cursor() as cursor:
				cursor_mysql.execute('UPDATE documento SET fk_processo = %s WHERE id = %s', [objeto_processo[0].id, documento_id])
			else:
				#with connection.cursor() as cursor:
				cursor_mysql.execute('INSERT INTO processo (numero) VALUES (%s)', [processo])
				cursor_mysql.execute('SELECT MAX(id) FROM processo')
				objeto_processo_id = cursor_mysql.fetchone()[0]
				cursor_mysql.execute('UPDATE documento SET fk_processo = %s WHERE id = %s', [objeto_processo_id, documento_id])

			objeto_processo = Processo.objects.using('postgresql').raw('SELECT * FROM processo WHERE numero = %s', [processo])
			if objeto_processo:
				#with connection.cursor() as cursor:
				cursor_postgresql.execute('UPDATE documento SET fk_processo = %s WHERE id = %s', [objeto_processo[0].id, documento_id])
			else:
				#with connection.cursor() as cursor:
				cursor_postgresql.execute('INSERT INTO processo (numero) VALUES (%s)', [processo])
				cursor_postgresql.execute('SELECT MAX(id) FROM processo')
				objeto_processo_id = cursor_postgresql.fetchone()[0]
				cursor_postgresql.execute('UPDATE documento SET fk_processo = %s WHERE id = %s', [objeto_processo_id, documento_id])

		#Salva o novo documento
		#documento.save()

		""" if (request.POST['prazo_01'] != ''):
			tipo_01 = request.POST['tipo_01']
			prazo_01 = request.POST['prazo_01']
			documento.prazo_set.create(tipo = tipo_01, vencimento = prazo_01)
		
		try:
			tipo_02 = request.POST['tipo_02']
			prazo_02 = request.POST['prazo_02']
			documento.prazo_set.create(tipo = tipo_02, vencimento = prazo_02)
		except:
			print("Prazo 02 não utilizado")
		
		try:
			tipo_03 = request.POST['tipo_03']
			prazo_03 = request.POST['prazo_03']
			documento.prazo_set.create(tipo = tipo_03, vencimento = prazo_03)
		except:
			print("Prazo 03 não utilizado") """
		indice = 1
		
		while True:
			tipo = "{}{}".format("tipo_", indice)
			data = "{}{}".format("prazo_", indice)
			prazo_tipo = request.POST.get(tipo, False)
			prazo_data = request.POST.get(data, False)

			if prazo_tipo and prazo_data:
				cursor_mysql.execute('INSERT INTO prazo '
										+ '(fk_documento, tipo, vencimento, encerrado, dilacao) '
									+ 'VALUES '
										+ '(%s, %s, %s, false, false)', [
																			documento_id,
																			prazo_tipo,
																			prazo_data,
																			])

				cursor_postgresql.execute('INSERT INTO prazo '
											+ '(fk_documento, tipo, vencimento, encerrado, dilacao) '
										+ 'VALUES '
											+ '(%s, %s, %s, false, false)', [
																				documento_id,
																				prazo_tipo,
																				prazo_data,
																				])
			else:
				break
			indice += 1

		#return HttpResponseRedirect(reverse('inout:index'))
		return redirect(reverse('inout:cadastrar'))

#Retorna um formulario preenchido com as informações de um documento já cadastrado
def editar_documento(request, documento_id):
	try:
		documento = Documento.objects.raw('SELECT * FROM documento WHERE id = %s', [documento_id])[0]
	except Documento.DoesNotExist:
		return redirect(reverse('inout:error_404_view'))
	
	contexto = {

inout/templates/inout/cadastrar.html
{% load staticfiles %}
{% include "header.html" %}

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">{{ titulo }}</h1>
          <div class="col-lg-12 mb-4">
            <div class="card shadow mb-4">
              <div class="col-lg-7">
                <div class="p-5">
                  <form class="user" action="{% url 'inout:salvarcadastro' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        <!--input type="number" class="form-control form-control-user" id="tipo_de_documento" name="tipo_de_documento" placeholder="Tipo" required /-->
                        <select class="form-control form-control-user-alternative" id="tipo_de_documento" name="tipo_de_documento" required />
                          <option value="0">Carta</option>
                          <option value="1">Convite</option>
                          <option value="2">Documento</option>
                          <option value="3">Email</option>
                          <option value="4">Mandado de Intimação</option>
                          <option value="5">Memorando</option>
                          <option value="6">Memorando Circular</option>
                          <option value="7">Movimentação da Solicitação</option>
                          <option value="8">Notificação</option>
                          <option value="9" selected>Ofício</option>
                          <option value="10">Ofício Circular</option>
                          <option value="11">Requerimento</option>
                          <option value="12">Outros</option>
                        </select>
                      </div>
                      <div class="col-sm-6">
                        <input type="text" class="form-control form-control-user" id="numero_do_documento" name="numero_do_documento" placeholder="n°" required />
                      </div>
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="orgao_expedidor_do_documento" name="orgao_expedidor_do_documento" placeholder="Expeditor" required />
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="assunto_do_documento" name="assunto_do_documento" placeholder="Assunto" required />
                    </div>
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="despacho_do_documento" name="despacho_do_documento" placeholder="Despacho" required />
                    </div>

                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" class="form-control form-control-user" id="numero_do_processo" name="numero_do_processo" placeholder="Processo n°" />
                      </div>
                    </div>

                    <div class="input_fields_wrap">
                      <div>
                        <div class="form-group row">
                          <div class="col-sm-6 mb-3 mb-sm-0">
                            <input type="text" class="form-control form-control-user" id="tipo_01" name="tipo_01" placeholder="Tipo" />
                          </div>
                          <div class="col-sm-6">
                            <input type="date" class="form-control form-control-user" id="prazo_01" name="prazo_01" placeholder="Data" />
                          </div>
                        </div>
                      </div>
                    </div>
                    <br/>
                    <div class="form-group row">
                      <div class="col-sm-6 mb-3 mb-sm-0">
                        <button class="add_field_button btn btn-primary btn-user btn-block">Novo Prazo</button>
                      </div>
                      <div class="col-sm-6">
                        <input class="btn btn-primary btn-user btn-block" type="submit" name="Cadastrar"/>
                      </div>
                    </div>
                    <!--button class="add_field_button btn btn-primary btn-user btn-block">Novo Prazo</button>
                    <input class="btn btn-primary btn-user btn-block" type="submit" name="Cadastrar"/-->
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

{% include "footer.html" %}