inOutServer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('inout.urls')),
    path('usuario/', include('usuario.urls'))
]

handler404 = 'inout.views.error_404_view'
handler500 = 'inout.views.error_500_view'

inout/urls.py
from django.urls import path
from django.conf.urls import url, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views
#from inout.views import lista_protocolos

app_name = "inout"
urlpatterns = [
	#path('', views.index, name = 'index'),
	#path('', views.login_view, name = 'login_view'),
	path('', views.login_view, name = 'login_view'),
	path('login', views.login_view, name = 'login_view'),
	path('login.html', views.login_view, name = 'login_view'),
	path('valida_login', views.valida_login, name = 'valida_login'),
	path('logout', views.logout_view, name = 'logout_view'),
	path('index', views.index, name = 'index'),
	path('index.html', views.index, name = 'index'),
	path('cadastrar', views.cadastrar, name = 'cadastrar'),
	path('cadastrar.html', views.cadastrar, name = 'cadastrar'),
	path('salvarcadastro', views.salvarcadastro, name = 'salvarcadastro'),
	path('<int:documento_id>/editar_documento', views.editar_documento, name = 'editar_documento'),
	path('<int:documento_id>/salvar_edicao_documento', views.salvar_edicao_documento, name = 'salvar_edicao_documento'),
	re_path(r'^protocolar_documento', views.protocolar_documento, name = "protocolar_documento"),
	re_path(r'^salvar_protocolo_documento', views.salvar_protocolo_documento, name = "salvar_protocolo_documento"),
	path('<int:protocolo_documento_id>/documento_entregue', views.documento_entregue, name = "documento_entregue"),
	path('listardocumentos', views.listardocumentos, name = 'listardocumentos'),
	path('listardocumentos.html', views.listardocumentos, name = 'listardocumentos'),
	path('<int:documento_id>/detalhesdocumento', views.detalhesdocumento, name = 'detalhesdocumento'),
	path('<int:documento_id>/detalhesdocumento.html', views.detalhesdocumento, name = 'detalhesdocumento'),
	path('<int:documento_id>/<int:prazo_id>/alterar_status_prazo', views.alterar_status_prazo, name = 'alterar_status_prazo'),
	path('listarprazos', views.listarprazos, name = 'listarprazos'),
	path('listarprazos.html', views.listarprazos, name = 'listarprazos'),
	path('listarprazosdodia', views.listarprazosdodia, name = 'listarprazosdodia'),
	path('listarprazosdodia.html', views.listarprazosdodia, name = 'listarprazosdodia'),
	path('listar_documentos_do_dia', views.listar_documentos_do_dia, name = 'listar_documentos_do_dia'),
	path('listar_documentos_da_semana', views.listar_documentos_da_semana, name = 'listar_documentos_da_semana'),
	path('listar_documentos_do_mes', views.listar_documentos_do_mes, name = 'listar_documentos_do_mes'),
	re_path(r'^novo_orgao', views.novo_orgao, name = 'novo_orgao'),
	re_path(r'^salvar_orgao', views.salvar_orgao, name = 'salvar_orgao'),
	re_path(r'^lista_orgaos', views.lista_orgaos , name = "lista_orgaos"),
	re_path(r'^novo_setor', views.novo_setor , name = "novo_setor"),
	re_path(r'^salvar_setor', views.salvar_setor , name = "salvar_setor"),
	re_path(r'^lista_setores', views.lista_setores , name = "lista_setores"),
	re_path(r'^novo_protocolo', views.novo_protocolo , name = "novo_protocolo"),
	re_path(r'^salvar_protocolo', views.salvar_protocolo , name = "salvar_protocolo"),
	re_path(r'^lista_protocolos_externos', views.lista_protocolos_externos , name = "lista_protocolos_externos"),
	re_path(r'^lista_protocolos_internos', views.lista_protocolos_internos , name = "lista_protocolos_internos"),
	re_path(r'^lista_protocolos_usf', views.lista_protocolos_usf , name = "lista_protocolos_usf"),
	re_path(r'^lista_protocolos', views.lista_protocolos.as_view(), name = "lista_protocolos"),
	re_path(r'^busca_numero_documento', views.busca_numero_documento, name = 'busca_numero_documento'),
	url(r'^api/chart/data/$', views.chart_data_linha.as_view()),
	url(r'^api/chart/pie/$', views.chart_data_pie.as_view()),
	#Falta implementar
	#re_path(r'^busca_avancada', views.busca_avancada , name = "busca_avancada"),
	re_path(r'^busca_avancada', views.busca_avancada.as_view() , name = "busca_avancada"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from django.conf.urls import url, re_path
from . import views

app_name = "usuario"
urlpatterns = [
    re_path(r'^cadastro_usuario/', views.cadastro_usuario, name = 'cadastro_usuario'),
    re_path(r'^salva_usuario/', views.salva_usuario, name = 'salva_usuario'),
    #re_path(r'^lista_usuarios', views.lista_usuarios, name = "lista_usuarios"),
    re_path(r'^lista_usuarios', views.lista_usuarios.as_view(), name = "lista_usuarios"),
]

usuario/views.py
from django.views.generic import ListView
from django.shortcuts import render, redirect
from inout.models import Lotacao, Orgao, Setor
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from datetime import timedelta
from django.db import connections
import datetime

cursor_mysql = connections['default'].cursor()
cursor_postgresql = connections['postgresql'].cursor()

# Create your views here.
def cadastro_usuario(request):
    lista_de_setores = Setor.objects.raw('SELECT * FROM setor')

    contexto = {
		'titulo': "Cadastrar novo usuário",
        'select': Lotacao(),
        'lista_de_orgaos': Orgao.objects.all(),
        'lista_de_setores': lista_de_setores,
	}

    return render(request, 'usuario/cadastro_usuario.html', contexto)

def salva_usuario(request):
    user = User.objects.db_manager('default').create_user(request.POST.get('username', False), password = request.POST.get('password', False), email = request.POST.get('email', False))
    user.first_name = request.POST.get('first_name', False)
    user.last_name = request.POST.get('last_name', False)
    user.save()

    user_postgresql = User.objects.db_manager('postgresql').create_user(request.POST.get('username', False), password = request.POST.get('password', False), email = request.POST.get('email', False))
    user_postgresql.first_name = request.POST.get('first_name', False)
    user_postgresql.last_name = request.POST.get('last_name', False)
    user_postgresql.save()

    """ setor = Setor()
    setor.orgao = Orgao.objects.get(pk = request.POST.get('orgao', False))
    setor.nome = request.POST.get('setor', False)
    setor.save()

    lotacao = Lotacao()
    lotacao.cargo = request.POST.get('cargo', False)
    lotacao.usuario = user
    lotacao.setor = setor
    lotacao.save() """

    setor = Setor.objects.using('default').raw('SELECT * FROM setor WHERE id = %s', [request.POST.get('setor', False)])
    cargo = request.POST.get('cargo', False)

    if setor and cargo:
        #with connection.cursor() as cursor:
        cursor_mysql.execute('INSERT INTO lotacao '
                                + '(fk_user, fk_setor, cargo, entrada) '
                            + 'VALUES '
                                + '(%s, %s, %s, %s)', [
                                                        user.id,
                                                        request.POST.get('setor', False),
                                                        cargo,
                                                        datetime.date.today(),
                                                        ])

        cursor_postgresql.execute('INSERT INTO lotacao '
                                    + '(fk_user, fk_setor, cargo, entrada) '
                                + 'VALUES '
                                    + '(%s, %s, %s, %s)', [
                                                            user.id,
                                                            request.POST.get('setor', False),
                                                            cargo,
                                                            datetime.date.today(),
                                                            ])


    
    else:
        messages.add_message(request, messages.ERROR, "Preencha todos os campos")

        return redirect(reverse('registration:cadastro_usuario'))

    messages.add_message(request, messages.SUCCESS, "Usuário cadastrado com sucesso")
    
    login(request, user)

    return redirect(reverse('inout:index'))

""" @login_required
def lista_usuarios(request):

	context = {
		'titulo': "Lista de usuários cadastrados",
	}

	return render(request, 'usuario/lista_usuarios.html', context) """

@method_decorator(login_required, name='dispatch')
class lista_usuarios(ListView):
	model = Lotacao
	template_name = 'usuario/lista_usuarios.html'

templates/usuario/cadastro_usuario.html
        {% extends 'base.html' %}
        {% block content %}

        <!-- Begin Page Content -->
        <div class="container-fluid">

        <!-- Page Heading -->
            <h1 class="h3 mb-4 text-gray-800">{{ titulo }}</h1>
            <div class="col-lg-12 mb-4">
                <div class="card shadow mb-4">
                    <div class="col-lg-7">
                        <div class="p-5">
                            <form class="user" action="{% url 'usuario:salva_usuario' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="first_name" name="first_name" placeholder="Nome" required >
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" id="last_name" name="last_name" placeholder="Sobrenome" required />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="username" name="username" placeholder="Nome de Usuário" required >
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="email" class="form-control form-control-user" id="email" name="email" placeholder="Email" required />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user" id="password" name="password" placeholder="Senha" required >
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user" id="confirma_password" name="confirma_password" placeholder="Repita sua Senha" required />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <select class="form-control form-control-user-alternative1" name="orgao" required >
                                            {% for orgao in lista_de_orgaos %}
                                                <option value="{{ orgao.id }}">{{ orgao.sigla }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-sm-6">
                                        {% if lista_de_setores %}
                                        <select class="form-control form-control-user-alternative1" name="setor" required >
                                            {% for setor in lista_de_setores %}
                                                <option value="{{ setor.id }}">{{ setor.sigla }} - {{ setor.fk_orgao.sigla }}</option>
                                            {% endfor %}
                                        </select>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <select class="form-control form-control-user-alternative1" name="cargo" required >
                                            {%for cargo in select.cargo_choices %}
                                                <option value="{{ cargo.0 }}">{{ cargo.1 }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input class="btn btn-primary btn-user btn-block" type="submit" value="Cadastrar"/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
        {% endblock %}

templates/usuario/lista_usuarios.html
        {% extends 'base.html' %}
        {% block content %}
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">{{ titulo }}</h1>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Resultados</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="display" id="tabela_datatables" >
                  <thead>
                    <tr>
                      <th>Nome</th>
                      <th>Email</th>
                      <th>Órgão</th>
                      <th>Setor</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for lotacao in lotacao_list %}
                      <tr>
                        <td>{{ lotacao.fk_user.first_name }}</td>
                        <td>{{ lotacao.fk_user.email }}</a></td>
                        <td>{{ lotacao.fk_setor.fk_orgao }}</td>
                        <td>{{ lotacao.fk_setor }}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                  <tfoot>
                    <tr>
                      <th>Nome</th>
                      <th>Email</th>
                      <th>Órgão</th>
                      <th>Setor</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->
        {% endblock %}