inOutServer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls import url, handler404, handler500
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('inout.urls')),
    path('usuario/', include('usuario.urls'))
]

handler404 = 'inout.views.error_404_view'
handler500 = 'inout.views.error_500_view'

inout/urls.py
from django.urls import path
from django.conf.urls import url, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views
#from inout.views import lista_protocolos

app_name = "inout"
urlpatterns = [
	#path('', views.index, name = 'index'),
	#path('', views.login_view, name = 'login_view'),
	path('', views.login_view, name = 'login_view'),
	path('login', views.login_view, name = 'login_view'),
	path('login.html', views.login_view, name = 'login_view'),
	path('valida_login', views.valida_login, name = 'valida_login'),
	path('logout', views.logout_view, name = 'logout_view'),
	path('index', views.index, name = 'index'),
	path('index.html', views.index, name = 'index'),
	path('cadastrar', views.cadastrar, name = 'cadastrar'),
	path('cadastrar.html', views.cadastrar, name = 'cadastrar'),
	path('salvarcadastro', views.salvarcadastro, name = 'salvarcadastro'),
	path('<int:documento_id>/editar_documento', views.editar_documento, name = 'editar_documento'),
	path('<int:documento_id>/salvar_edicao_documento', views.salvar_edicao_documento, name = 'salvar_edicao_documento'),
	re_path(r'^protocolar_documento', views.protocolar_documento, name = "protocolar_documento"),
	re_path(r'^salvar_protocolo_documento', views.salvar_protocolo_documento, name = "salvar_protocolo_documento"),
	path('<int:protocolo_documento_id>/documento_entregue', views.documento_entregue, name = "documento_entregue"),
	path('listardocumentos', views.listardocumentos, name = 'listardocumentos'),
	path('listardocumentos.html', views.listardocumentos, name = 'listardocumentos'),
	path('<int:documento_id>/detalhesdocumento', views.detalhesdocumento, name = 'detalhesdocumento'),
	path('<int:documento_id>/detalhesdocumento.html', views.detalhesdocumento, name = 'detalhesdocumento'),
	path('<int:documento_id>/<int:prazo_id>/alterar_status_prazo', views.alterar_status_prazo, name = 'alterar_status_prazo'),
	path('listarprazos', views.listarprazos, name = 'listarprazos'),
	path('listarprazos.html', views.listarprazos, name = 'listarprazos'),
	path('listarprazosdodia', views.listarprazosdodia, name = 'listarprazosdodia'),
	path('listarprazosdodia.html', views.listarprazosdodia, name = 'listarprazosdodia'),
	path('listar_documentos_do_dia', views.listar_documentos_do_dia, name = 'listar_documentos_do_dia'),
	path('listar_documentos_da_semana', views.listar_documentos_da_semana, name = 'listar_documentos_da_semana'),
	path('listar_documentos_do_mes', views.listar_documentos_do_mes, name = 'listar_documentos_do_mes'),
	re_path(r'^novo_orgao', views.novo_orgao, name = 'novo_orgao'),
	re_path(r'^salvar_orgao', views.salvar_orgao, name = 'salvar_orgao'),
	re_path(r'^lista_orgaos', views.lista_orgaos , name = "lista_orgaos"),
	re_path(r'^novo_setor', views.novo_setor , name = "novo_setor"),
	re_path(r'^salvar_setor', views.salvar_setor , name = "salvar_setor"),
	re_path(r'^lista_setores', views.lista_setores , name = "lista_setores"),
	re_path(r'^novo_protocolo', views.novo_protocolo , name = "novo_protocolo"),
	re_path(r'^salvar_protocolo', views.salvar_protocolo , name = "salvar_protocolo"),
	re_path(r'^lista_protocolos_externos', views.lista_protocolos_externos , name = "lista_protocolos_externos"),
	re_path(r'^lista_protocolos_internos', views.lista_protocolos_internos , name = "lista_protocolos_internos"),
	re_path(r'^lista_protocolos_usf', views.lista_protocolos_usf , name = "lista_protocolos_usf"),
	re_path(r'^lista_protocolos', views.lista_protocolos.as_view(), name = "lista_protocolos"),
	re_path(r'^busca_numero_documento', views.busca_numero_documento, name = 'busca_numero_documento'),
	url(r'^api/chart/data/$', views.chart_data_linha.as_view()),
	url(r'^api/chart/pie/$', views.chart_data_pie.as_view()),
	#Falta implementar
	#re_path(r'^busca_avancada', views.busca_avancada , name = "busca_avancada"),
	re_path(r'^busca_avancada', views.busca_avancada.as_view() , name = "busca_avancada"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inout/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Documento(models.Model):
    fk_user = models.ForeignKey(User, models.DO_NOTHING, db_column='fk_user')
    fk_processo = models.ForeignKey('Processo', models.DO_NOTHING, db_column='fk_processo', blank=True, null=True)
    data_de_recebimento = models.DateField()
    tipos_choices = [
		(1, 'Carta'),
		(2, 'Convite'),
		(3, 'Documento'),
		(4, 'Email'),
		(5, 'Mandado de Intimação'),
		(6, 'Memorando'),
		(7, 'Memorando Circular'),
		(8, 'Movimentação da Solicitação'),
		(9, 'Notificação'),
		(10, 'Ofício'),
		(11, 'Ofício Circular'),
		(12, 'Requerimento'),
		(13, 'Outro'),
	]
    tipo = models.IntegerField(choices = tipos_choices, default = 10)
    numero = models.CharField(max_length=30)
    emissor = models.CharField(max_length=50)
    assunto = models.CharField(max_length=1000)
    despacho = models.CharField(max_length=200)
    entrega_pessoal = models.BooleanField()
    pdf = models.FileField(upload_to = 'pdf/', null = True, blank = True)

    def __str__(self):
        return "{} {} - {}".format(self.tipo, self.numero, self.emissor)
    
    def tipo_do_documento(self):
        return self.tipos_choices[self.tipo - 1][1]

    class Meta:
        db_table = 'documento'


class Livro(models.Model):
    fk_setor = models.ForeignKey('Setor', models.DO_NOTHING, db_column='fk_setor')
    tipos_choices = [
		(1, "Externo"),
		(2, "Interno"),
		(3, "USF"),
	]
    tipo = models.IntegerField(choices = tipos_choices, default = 2)
    ano = models.IntegerField()
    volume = models.IntegerField()
    encerrado = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return "Protocolo {} {} Volume {}".format(self.tipos_choices[self.tipo - 1][1], self.ano, self.volume)

    def nome_do_livro(self):
        return "{} {} {} Volume {}".format(self.fk_setor.sigla, self.tipos_choices[self.tipo - 1][1], self.ano, self.volume)

    def tipo_do_livro(self):
        return self.tipos_choices[self.tipo - 1][1]

    class Meta:
        db_table = 'livro'


class Lotacao(models.Model):
    fk_user = models.ForeignKey(User, models.DO_NOTHING, db_column='fk_user')
    fk_setor = models.ForeignKey('Setor', models.DO_NOTHING, db_column='fk_setor')
    cargo_choices = [
		(1, "Arquiteto"),
		(2, "Assistente Administrativo"),
		(3, "Chefe de Gabinete"),
		(4, "Diretor"),
		(5, "Estagiário"),
		(6, "Fiscal"),
		(7, "Recepcionista"),
		(8, "Secretário"),
		(9, "Técnico em Informática"),
	]
    cargo = models.IntegerField(choices = cargo_choices)
    entrada = models.DateField()
    saida = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'lotacao'


class Orgao(models.Model):
    nome = models.CharField(max_length=50)
    sigla = models.CharField(max_length=10)
    esfera_choices = [
		(1, "Estadual"),
		(2, "Federal"),
		(3, "Municipal"),
	]
    esfera = models.IntegerField(choices = esfera_choices)
    estado_choices = [
		(1, "Acre (AC)"),
		(2, "Alagoas (AL)"),
		(3, "Amapá (AP)"),
		(4, "Amazonas (AM)"),
		(5, "Bahia (BA)"),
		(6, "Ceará (CE)"),
		(7, "Distrito Federal (DF)"),
		(8, "Espírito Santo (ES)"),
		(9, "Goiás (GO)"),
		(10, "Maranhão (MA)"),
		(11, "Mato Grosso (MT)"),
		(12, "Mato Grosso do Sul (MS)"),
		(13, "Minas Gerais (MG)"),
		(14, "Pará (PA)"),
		(15, "Paraíba (PB)"),
		(16, "Paraná (PR)"),
		(17, "Pernambuco (PE)"),
		(18, "Piauí (PI)"),
		(19, "Rio de Janeiro (RJ)"),
		(20, "Rio Grande do Norte (RN)"),
		(21, "Rio Grande do Sul (RS)"),
		(22, "Rondônia (RO)"),
		(23, "Roraima (RR)"),
		(24, "Santa Catarina (SC)"),
		(25, "São Paulo (SP)"),
		(26, "Sergipe (SE)"),
		(27, "Tocantins (TO)"),
	]
    estado = models.IntegerField(choices = estado_choices, default=20)
    municipio = models.CharField(max_length=32)
    ativo = models.BooleanField()

    def __str__(self):
        return self.sigla

    class Meta:
        db_table = 'orgao'


class Pagina(models.Model):
    fk_livro = models.ForeignKey(Livro, models.DO_NOTHING, db_column='fk_livro')
    numero = models.IntegerField()
    
    def __str__(self):
        return self.numero
    
    class Meta:
        db_table = 'pagina'


class Prazo(models.Model):
    fk_documento = models.ForeignKey(Documento, models.DO_NOTHING, db_column='fk_documento')
    tipo_choices = [
        (1, "Audiência"),
        (2, "Evento"),
        (3, "Fiscalização"),
        (4, "Palestra"),
        (5, "Resposta"),
        (6, "Reunião"),
        (7, "Vistoria"),
    ]
    tipo = models.IntegerField(choices = tipo_choices, default = 5)
    vencimento = models.DateField()
    encerrado = models.IntegerField()
    dilacao = models.IntegerField()
    quantidade_de_dilacoes = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.tipo, self.vencimento)

    def tipo_do_prazo(self):
        return self.tipo_choices[self.tipo - 1][1]

    class Meta:
        db_table = 'prazo'


class Processo(models.Model):
    numero = models.CharField(max_length=21)

    def __str__(self):
        return self.numero

    class Meta:
        db_table = 'processo'


class Protocolo(models.Model):
    fk_documento = models.ForeignKey(Documento, models.DO_NOTHING, db_column='fk_documento')
    fk_setor_origem = models.ForeignKey('Setor', models.DO_NOTHING, db_column='fk_setor_origem', related_name = 'setor_de_origem')
    fk_setor_destino = models.ForeignKey('Setor', models.DO_NOTHING, db_column='fk_setor_destino', related_name = 'setor_de_destino')
    fk_pagina = models.ForeignKey(Pagina, models.DO_NOTHING, db_column='fk_pagina')
    entregue = models.IntegerField()
    data_da_entrega = models.DateField(blank=True, null=True)

    def __str__(self):
        return "fuck"

    class Meta:
        db_table = 'protocolo'


class Setor(models.Model):
    fk_orgao = models.ForeignKey(Orgao, models.DO_NOTHING, db_column='fk_orgao')
    nome = models.CharField(max_length=50)
    sigla = models.CharField(max_length=10)
    ativo = models.BooleanField()

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'setor'

usuario/views.py
from django.views.generic import ListView
from django.shortcuts import render, redirect
from inout.models import Lotacao, Orgao, Setor
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from datetime import timedelta
from django.db import connections
import datetime

cursor_mysql = connections['default'].cursor()
cursor_postgresql = connections['postgresql'].cursor()

# Create your views here.
def cadastro_usuario(request):
    lista_de_setores = Setor.objects.raw('SELECT * FROM setor')

    contexto = {
		'titulo': "Cadastrar novo usuário",
        'select': Lotacao(),
        'lista_de_orgaos': Orgao.objects.all(),
        'lista_de_setores': lista_de_setores,
	}

    return render(request, 'usuario/cadastro_usuario.html', contexto)

def salva_usuario(request):
    user = User.objects.db_manager('default').create_user(request.POST.get('username', False), password = request.POST.get('password', False), email = request.POST.get('email', False))
    user.first_name = request.POST.get('first_name', False)
    user.last_name = request.POST.get('last_name', False)
    user.save()

    user_postgresql = User.objects.db_manager('postgresql').create_user(request.POST.get('username', False), password = request.POST.get('password', False), email = request.POST.get('email', False))
    user_postgresql.first_name = request.POST.get('first_name', False)
    user_postgresql.last_name = request.POST.get('last_name', False)
    user_postgresql.save()

    """ setor = Setor()
    setor.orgao = Orgao.objects.get(pk = request.POST.get('orgao', False))
    setor.nome = request.POST.get('setor', False)
    setor.save()

    lotacao = Lotacao()
    lotacao.cargo = request.POST.get('cargo', False)
    lotacao.usuario = user
    lotacao.setor = setor
    lotacao.save() """

    setor = Setor.objects.using('default').raw('SELECT * FROM setor WHERE id = %s', [request.POST.get('setor', False)])
    cargo = request.POST.get('cargo', False)

    if setor and cargo:
        #with connection.cursor() as cursor:
        cursor_mysql.execute('INSERT INTO lotacao '
                                + '(fk_user, fk_setor, cargo, entrada) '
                            + 'VALUES '
                                + '(%s, %s, %s, %s)', [
                                                        user.id,
                                                        request.POST.get('setor', False),
                                                        cargo,
                                                        datetime.date.today(),
                                                        ])

        cursor_postgresql.execute('INSERT INTO lotacao '
                                    + '(fk_user, fk_setor, cargo, entrada) '
                                + 'VALUES '
                                    + '(%s, %s, %s, %s)', [
                                                            user.id,
                                                            request.POST.get('setor', False),
                                                            cargo,
                                                            datetime.date.today(),
                                                            ])


    
    else:
        messages.add_message(request, messages.ERROR, "Preencha todos os campos")

        return redirect(reverse('registration:cadastro_usuario'))

    messages.add_message(request, messages.SUCCESS, "Usuário cadastrado com sucesso")
    
    login(request, user)

    return redirect(reverse('inout:index'))

""" @login_required
def lista_usuarios(request):

	context = {
		'titulo': "Lista de usuários cadastrados",
	}

	return render(request, 'usuario/lista_usuarios.html', context) """

@method_decorator(login_required, name='dispatch')
class lista_usuarios(ListView):
	model = Lotacao
	template_name = 'usuario/lista_usuarios.html'

templates/inout/busca_avancada.html
        {% extends 'base.html' %}
        {% block content %}

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">{{ titulo }}</h1>
          <div class="col-lg-12 mb-4">
            <div class="card shadow mb-4">
              <div class="col-lg-7">
                <div class="p-5">
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->
        {% endblock %}

templates/inout/detalhesdocumento.html
{% extends 'base.html' %}
{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">
  <h1 class="h3 mb-4 text-gray-800">Detalhes</h1>
  <div class="row">
    <div class="col-lg-6 mb-4">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">{{ documento.tipo_do_documento }} {{ documento.numero }} - {{ documento.emissor }}</h6>
        </div>
        <div class="card-body">
          {% if documento %}
          <!-- Page Heading -->
          <label>Data Recebimento: </label> {{ documento.data_de_recebimento|date:'d/m/Y' }}
          <br />
          <label>Tipo: </label> {{ documento.tipo_do_documento }}
          <br />
          <label>Número: </label> {{ documento.numero }}
          <br />
          <label>Expedido: </label> {{ documento.emissor }}
          <br />
          <label>Assunto: </label> {{ documento.assunto }}
          <br />
          <label>Despacho: </label> {{ documento.despacho }}
          <br />
          <label>N° Processo: </label> {{ documento.fk_processo.numero }}
          <br />
          <label>Cadastrado por: </label> {{ documento.fk_user.username }}
          <br />
          {% if documento.entrega_pessoal == True  %}
          <label><strong>ENTREGA PESSOAL</strong></label>
          {% endif %}
          <br />
          <div class="row">
            <div class="col-lg-6 mb-4">
              <div class="row">
                {% for prazo in documento.prazo_set.all %}
                <div class="col-lg-6 mb-4">
                  {% if prazo.encerrado == True %}
                  <div class="card bg-success text-white shadow">
                    <div class="card-body">
                      {{ prazo.vencimento|date:'d/m/Y' }}
                      <div class="text-white-50 small">{{ prazo.tipo_do_prazo }}</div>
                      <!--a id="removeStyleLink" href="{% url 'inout:alterar_status_prazo' documento.id prazo.id %}" class="bg-success card text-white shadow" />Encerrar</a-->
                      <span class="bg-success card text-white shadow centralizaTexto" />Encerrado</span>
                    </div>
                    <!--input type="submit" value="Encerrar"/-->
                    <!-- CASO O BOTÃO DENTRO N FUNCIONE, USAR ESSE -->
                  </div>
                  {% elif prazo.encerrado == False and prazo.vencimento|date:'d/m/Y' >= data_de_hoje|date:'d/m/Y' %}
                  <div class="card bg-warning text-white shadow">
                    <div class="card-body">
                      {{ prazo.vencimento|date:'d/m/Y' }}
                      <div class="text-white-50 small">{{ prazo.tipo_do_prazo }}</div>
                      <a id="removeStyleLink" href="{% url 'inout:alterar_status_prazo' documento.id prazo.id %}"
                        class="bg-warning card text-white shadow centralizaTexto" />Encerrar</a>
                    </div>
                    <!--input type="submit" value="Encerrar"/-->
                    <!-- CASO O BOTÃO DENTRO N FUNCIONE, USAR ESSE -->
                  </div>
                  {% elif prazo.encerrado == False and prazo.vencimento|date:'d/m/Y' < data_de_hoje|date:'d/m/Y' %}
                  <div class="card bg-danger text-white shadow">
                    <div class="card-body">
                      {{ prazo.vencimento|date:'d/m/Y' }}
                      <div class="text-white-50 small">{{ prazo.tipo_do_prazo }}</div>
                      <a id="removeStyleLink" href="{% url 'inout:alterar_status_prazo' documento.id prazo.id %}"
                        class="bg-danger card text-white shadow centralizaTexto" />Encerrar</a>
                    </div>
                    <!--input type="submit" value="Encerrar"/-->
                    <!-- CASO O BOTÃO DENTRO N FUNCIONE, USAR ESSE -->
                  </div>
                  {% endif %}
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% if protocolo_documento %}
    <div class="col-lg-6">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Protocolo</h6>
        </div>
        <div class="card-body">
          <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
              <label>Origem: </label> {{ protocolo_documento.fk_setor_origem.sigla }}
            </div>
            <div class="col-sm-6">
              <label>Destino: </label> {{ protocolo_documento.fk_setor_destino.sigla }}
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
              <label>Livro: </label> {{ protocolo_documento.fk_pagina.fk_livro.nome_do_livro }}
            </div>
            <div class="col-sm-6">
              <label>Pagina: </label> {{ protocolo_documento.fk_pagina.numero }}
            </div>
          </div>
          {% if protocolo_documento.entregue == False %}
          <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <a id="removeStyleLink" href="{% url 'inout:documento_entregue' protocolo_documento.id %}" class="bg-danger card text-white shadow centralizaTexto" >Entregue</a>
              <!--input class="btn btn-primary btn-user btn-block" type="submit" value="Entregue" /-->
            </div>
          </div>
          {% else %}
          <div class="form-group row">
              <div class="col-sm-6">
                  <label>Data de Entrega: </label> {{ protocolo_documento.data_da_entrega|date:'d/m/Y' }}
              </div>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% endif %}
  </div>
  <div>
    <div>
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">{{ documento.tipo_do_documento }} {{ documento.numero }}</h6>
        </div>
        <div class="card-body">
            <!-- <embed src="https://suap.ifrn.edu.br/media/upload/baseconhecimento/anexos/Novo_processo_de_verificacao-a8b2765f996042d78b473bf976ad11eb.pdf" type="application/pdf"> -->
            <embed src="{{ documento.pdf.url }}" type="application/pdf">
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.container-fluid -->
{% endblock %}

templates/inout/editar.html
        {% extends 'base.html' %}
        {% block content %}

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">{{ titulo }}</h1>

          <div class="col-lg-7">
            <div class="p-5">
              {% if documento %}
              <form class="user" action="{% url 'inout:salvar_edicao_documento' documento.id %}" method="POST">
                {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="tipo_de_documento" name="tipo_de_documento" value="{{ documento.tipo }}" required />
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="numero_do_documento" name="numero_do_documento" value="{{ documento.numero }}" required />
                  </div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control form-control-user" id="orgao_expedidor_do_documento" name="orgao_expedidor_do_documento" value="{{ documento.emissor }}" required />
                </div>
                <div class="form-group">
                  <input type="text" class="form-control form-control-user" id="assunto_do_documento" name="assunto_do_documento" value="{{ documento.assunto }}" required />
                </div>
                <div class="form-group">
                  <input type="text" class="form-control form-control-user" id="despacho_do_documento" name="despacho_do_documento" value="{{ documento.despacho }}" required />
                </div>

                <br/>
                <div class="form-group row">
                  <div class="col-sm-6">
                    <input class="btn btn-primary btn-user btn-block" type="submit" name="Alterar"/>
                  </div>
                </div>
              </form>
              {% endif %}
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->
        {% endblock %}

templates/inout/lista_protocolos.html
        {% extends 'base.html' %}
        {% block content %}

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">{{ titulo }}</h1>
          <div class="col-lg-12 mb-4">
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Resultados</h6>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="display" id="tabela_datatables" >
                    <thead>
                      <tr>
                        <th>Setor</th>
                        <th>Ano</th>
                        <th>Tipo</th>
                        <th>Volume</th>
                        <th>Encerrado</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for livro in livro_list %}
                        <tr>
                          <td>{{ livro.fk_setor.sigla }}</td>
                          <td>{{ livro.ano }}</td>
                          <td>{{ livro.tipo_do_livro }}</td>
                          <td>{{ livro.volume }}</td>
                          <td>
                            {% if livro.encerrado == 1 %}
                              <img src="https://img.icons8.com/cute-clipart/32/000000/checked.png">
                            {% else %}
                            <img src="https://img.icons8.com/cute-clipart/32/000000/cancel.png">
                            {% endif %}
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Setor</th>
                        <th>Ano</th>
                        <th>Tipo</th>
                        <th>Volume</th>
                        <th>Encerrado</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->
        {% endblock %}

templates/inout/listardocumentos.html
        {% extends 'base.html' %}
        {% block content %}

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">{{ titulo }}</h1>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Resultados</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="display" id="tabela_datatables" >
                  <thead>
                    <tr>
                      <th>Data Recebimento</th>
                      <th>Tipo</th>
                      <th>Número</th>
                      <th>Expedido</th>
                      <th>Tipo Prazo</th>
                      <th>Prazo</th>
                      <th>Editar</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for documento in lista_de_documentos %}
                      <tr>
                        <td>{{ documento.data_de_recebimento|date:'d/m/Y' }}</td>
                        <td>{{ documento.tipo_do_documento }}</a></td>
                        <td><a href="{% url 'inout:detalhesdocumento' documento.id %}">{{ documento.numero }}</a></td>
                        <td>{{ documento.emissor }}</td>
                        <td>{% for prazo in documento.prazo_set.all %}
                          <!--{% if prazo.vencimento|date:'d/m/Y' != timezone.now|date:'d/m/Y' %}-->
                            {{ prazo.tipo_do_prazo }}
                          <!--{% endif %}-->
                          <br/>
                        {% endfor %}</td>
                        <td>{% for prazo in documento.prazo_set.all %}
                          {{ prazo.vencimento|date:'d/m/Y' }}
                          <br/>
                        {% endfor %}</td>
                        <td><a href="{% url 'inout:editar_documento' documento.id %}"><img src="https://img.icons8.com/cotton/32/000000/multi-edit.png" /></a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
                  <tfoot>
                    <tr>
                      <th>Data Recebimento</th>
                      <th>Tipo</th>
                      <th>Número</th>
                      <th>Expedido</th>
                      <th>Tipo Prazo</th>
                      <th>Prazo</th>
                      <th>Editar</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.container-fluid -->
        {% endblock %}